/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsSearchV2MusicArtistInformation
 */
export interface OmbiCoreModelsSearchV2MusicArtistInformation {
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  name?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  id?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  startYear?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  endYear?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  isEnded?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  type?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  country?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  region?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  disambiguation?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  banner?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  logo?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  poster?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  fanArt?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  overview?: any | null;
  /**
   *
   * @type {Array&lt;OmbiCoreModelsSearchV2MusicReleaseGroup&gt;}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  releaseGroups?: any | null;
  /**
   *
   * @type {OmbiCoreModelsSearchV2MusicArtistLinks}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  links?: any | null;
  /**
   *
   * @type {Array&lt;OmbiCoreModelsSearchV2MusicBandMember&gt;}
   * @memberof OmbiCoreModelsSearchV2MusicArtistInformation
   */
  members?: any | null;
}
