/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiModelsPresetThemeViewModel
 */
export interface OmbiModelsPresetThemeViewModel {
  /**
   *
   * @type {string}
   * @memberof OmbiModelsPresetThemeViewModel
   */
  fullName?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsPresetThemeViewModel
   */
  displayName?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsPresetThemeViewModel
   */
  version?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsPresetThemeViewModel
   */
  url?: any | null;
}
