/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiStoreEntitiesRequestsIssues
 */
export interface OmbiStoreEntitiesRequestsIssues {
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  title?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesRequestType}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  requestType?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  providerId?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  requestId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  subject?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  description?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  issueCategoryId?: any;
  /**
   *
   * @type {OmbiStoreEntitiesRequestsIssueCategory}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  issueCategory?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesRequestsIssueStatus}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  status?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  resovledDate?: any | null;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  createdDate?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  userReportedId?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesOmbiUser}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  userReported?: any | null;
  /**
   *
   * @type {Array&lt;OmbiStoreEntitiesRequestsIssueComments&gt;}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  comments?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsIssues
   */
  id?: any;
}
