/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiApiCouchPotatoModelsProfileList
 */
export interface OmbiApiCouchPotatoModelsProfileList {
  /**
   *
   * @type {boolean}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  core?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  hide?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  rev?: any | null;
  /**
   *
   * @type {Array&lt;boolean&gt;}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  finish?: any | null;
  /**
   *
   * @type {Array&lt;string&gt;}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  qualities?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  id?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  t?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  label?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  minimumScore?: any;
  /**
   *
   * @type {Array&lt;number&gt;}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  stopAfter?: any | null;
  /**
   *
   * @type {Array&lt;any&gt;}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  waitFor?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  order?: any;
  /**
   *
   * @type {Array&lt;any&gt;}
   * @memberof OmbiApiCouchPotatoModelsProfileList
   */
  threeD?: any | null;
}
