/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiSettingsSettingsModelsExternalLidarrSettings
 */
export interface OmbiSettingsSettingsModelsExternalLidarrSettings {
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  enabled?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  apiKey?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  defaultQualityProfile?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  defaultRootPath?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  albumFolder?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  metadataProfileId?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  addOnly?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  ssl?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  subDir?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  ip?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  port?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  fullUri?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsExternalLidarrSettings
   */
  id?: any;
}
