/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiApiRadarrModelsRadarrRootFolder
 */
export interface OmbiApiRadarrModelsRadarrRootFolder {
  /**
   *
   * @type {number}
   * @memberof OmbiApiRadarrModelsRadarrRootFolder
   */
  id?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiRadarrModelsRadarrRootFolder
   */
  path?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiRadarrModelsRadarrRootFolder
   */
  freespace?: any;
}
