/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreSettingsModelsExternalEmbySettings
 */
export interface OmbiCoreSettingsModelsExternalEmbySettings {
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsExternalEmbySettings
   */
  enable?: any;
  /**
   *
   * @type {Array&lt;OmbiCoreSettingsModelsExternalEmbyServers&gt;}
   * @memberof OmbiCoreSettingsModelsExternalEmbySettings
   */
  servers?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreSettingsModelsExternalEmbySettings
   */
  id?: any;
}
