/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsUIRequestsViewModel1OmbiStoreEntitiesRequestsAlbumRequestOmbiStoreVersion3000CultureneutralPublicKeyTokennull
 */
export interface OmbiCoreModelsUIRequestsViewModel1OmbiStoreEntitiesRequestsAlbumRequestOmbiStoreVersion3000CultureneutralPublicKeyTokennull {
  /**
   *
   * @type {Array&lt;OmbiStoreEntitiesRequestsAlbumRequest&gt;}
   * @memberof OmbiCoreModelsUIRequestsViewModel1OmbiStoreEntitiesRequestsAlbumRequestOmbiStoreVersion3000CultureneutralPublicKeyTokennull
   */
  collection?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsUIRequestsViewModel1OmbiStoreEntitiesRequestsAlbumRequestOmbiStoreVersion3000CultureneutralPublicKeyTokennull
   */
  total?: any;
}
