/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiStoreEntitiesRequestsIssueComments
 */
export interface OmbiStoreEntitiesRequestsIssueComments {
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsIssueComments
   */
  userId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsIssueComments
   */
  comment?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsIssueComments
   */
  issuesId?: any | null;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsIssueComments
   */
  date?: any;
  /**
   *
   * @type {OmbiStoreEntitiesRequestsIssues}
   * @memberof OmbiStoreEntitiesRequestsIssueComments
   */
  issues?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesOmbiUser}
   * @memberof OmbiStoreEntitiesRequestsIssueComments
   */
  user?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsIssueComments
   */
  id?: any;
}
