/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreProcessorUpdateModel
 */
export interface OmbiCoreProcessorUpdateModel {
  /**
   *
   * @type {string}
   * @memberof OmbiCoreProcessorUpdateModel
   */
  updateVersionString?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreProcessorUpdateModel
   */
  updateVersion?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiCoreProcessorUpdateModel
   */
  updateDate?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreProcessorUpdateModel
   */
  updateAvailable?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreProcessorUpdateModel
   */
  changeLogs?: any | null;
  /**
   *
   * @type {Array&lt;OmbiScheduleProcessorDownloads&gt;}
   * @memberof OmbiCoreProcessorUpdateModel
   */
  downloads?: any | null;
}
