/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsRequestsRequestCountModel
 */
export interface OmbiCoreModelsRequestsRequestCountModel {
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsRequestsRequestCountModel
   */
  pending?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsRequestsRequestCountModel
   */
  approved?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsRequestsRequestCountModel
   */
  available?: any;
}
