/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreSettingsModelsExternalTheMovieDbSettings
 */
export interface OmbiCoreSettingsModelsExternalTheMovieDbSettings {
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsExternalTheMovieDbSettings
   */
  showAdultMovies?: any;
  /**
   *
   * @type {Array&lt;number&gt;}
   * @memberof OmbiCoreSettingsModelsExternalTheMovieDbSettings
   */
  excludedKeywordIds?: any | null;
  /**
   *
   * @type {Array&lt;number&gt;}
   * @memberof OmbiCoreSettingsModelsExternalTheMovieDbSettings
   */
  excludedMovieGenreIds?: any | null;
  /**
   *
   * @type {Array&lt;number&gt;}
   * @memberof OmbiCoreSettingsModelsExternalTheMovieDbSettings
   */
  excludedTvGenreIds?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreSettingsModelsExternalTheMovieDbSettings
   */
  id?: any;
}
