/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsRecentlyAddedMovieModel
 */
export interface OmbiCoreModelsRecentlyAddedMovieModel {
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  id?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  title?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  overview?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  imdbId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  tvDbId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  theMovieDbId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  releaseYear?: any | null;
  /**
   *
   * @type {Date}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  addedAt?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsRecentlyAddedMovieModel
   */
  quality?: any | null;
}
