/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreSettingsModelsExternalJellyfinServers
 */
export interface OmbiCoreSettingsModelsExternalJellyfinServers {
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  serverId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  name?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  apiKey?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  administratorId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  serverHostname?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  enableEpisodeSearching?: any;
  /**
   *
   * @type {Array&lt;OmbiCoreSettingsModelsExternalJellyfinSelectedLibraries&gt;}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  jellyfinSelectedLibraries?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  ssl?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  subDir?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  ip?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  port?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  fullUri?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreSettingsModelsExternalJellyfinServers
   */
  id?: any;
}
