/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreSettingsModelsExternalPlexServers
 */
export interface OmbiCoreSettingsModelsExternalPlexServers {
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  name?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  plexAuthToken?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  machineIdentifier?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  episodeBatchSize?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  serverHostname?: any | null;
  /**
   *
   * @type {Array&lt;OmbiCoreSettingsModelsExternalPlexSelectedLibraries&gt;}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  plexSelectedLibraries?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  ssl?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  subDir?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  ip?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  port?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  fullUri?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreSettingsModelsExternalPlexServers
   */
  id?: any;
}
