/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsSearchV2CreditsViewModel
 */
export interface OmbiCoreModelsSearchV2CreditsViewModel {
  /**
   *
   * @type {Array&lt;OmbiCoreModelsSearchV2FullMovieCastViewModel&gt;}
   * @memberof OmbiCoreModelsSearchV2CreditsViewModel
   */
  cast?: any | null;
  /**
   *
   * @type {Array&lt;OmbiCoreModelsSearchV2FullMovieCrewViewModel&gt;}
   * @memberof OmbiCoreModelsSearchV2CreditsViewModel
   */
  crew?: any | null;
}
