/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
 */
export interface OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings {
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
   */
  enabled?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
   */
  webhookUrl?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
   */
  username?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
   */
  icon?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
   */
  hideUser?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
   */
  webHookId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
   */
  token?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsNotificationsDiscordNotificationSettings
   */
  id?: any;
}
