/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsSearchV2NetworkViewModel
 */
export interface OmbiCoreModelsSearchV2NetworkViewModel {
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsSearchV2NetworkViewModel
   */
  id?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2NetworkViewModel
   */
  name?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2NetworkViewModel
   */
  country?: any | null;
}
