/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiApiTheMovieDbModelsActorCredits
 */
export interface OmbiApiTheMovieDbModelsActorCredits {
  /**
   *
   * @type {Array&lt;OmbiApiTheMovieDbModelsCast&gt;}
   * @memberof OmbiApiTheMovieDbModelsActorCredits
   */
  cast?: any | null;
  /**
   *
   * @type {Array&lt;OmbiApiTheMovieDbModelsCrew&gt;}
   * @memberof OmbiApiTheMovieDbModelsActorCredits
   */
  crew?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiTheMovieDbModelsActorCredits
   */
  id?: any;
}
