/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsUINewsletterNotificationViewModel
 */
export interface OmbiCoreModelsUINewsletterNotificationViewModel {
  /**
   *
   * @type {OmbiStoreEntitiesNotificationTemplates}
   * @memberof OmbiCoreModelsUINewsletterNotificationViewModel
   */
  notificationTemplate?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsUINewsletterNotificationViewModel
   */
  disableTv?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsUINewsletterNotificationViewModel
   */
  disableMovies?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsUINewsletterNotificationViewModel
   */
  disableMusic?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsUINewsletterNotificationViewModel
   */
  enabled?: any;
  /**
   *
   * @type {Array&lt;string&gt;}
   * @memberof OmbiCoreModelsUINewsletterNotificationViewModel
   */
  externalEmails?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsUINewsletterNotificationViewModel
   */
  id?: any;
}
