/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiSettingsSettingsModelsJobSettings
 */
export interface OmbiSettingsSettingsModelsJobSettings {
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  embyContentSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  jellyfinContentSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  sonarrSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  radarrSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  plexContentSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  plexRecentlyAddedSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  couchPotatoSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  automaticUpdater?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  userImporter?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  sickRageSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  newsletter?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  lidarrArtistSync?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  issuesPurge?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  retryRequests?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  mediaDatabaseRefresh?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  autoDeleteRequests?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsJobSettings
   */
  id?: any;
}
