/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsSearchV2MusicReleaseGroup
 */
export interface OmbiCoreModelsSearchV2MusicReleaseGroup {
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  id?: any;
  /**
   *
   * @type {OmbiStoreEntitiesRequestType}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  type?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  title?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  releaseDate?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  releaseType?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  percentOfTracks?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  monitored?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  partiallyAvailable?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  fullyAvailable?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  approved?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  denied?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  deniedReason?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  requested?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  requestId?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  available?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  plexUrl?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  embyUrl?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  jellyfinUrl?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  quality?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  imdbId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  theTvDbId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  theMovieDbId?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  subscribed?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2MusicReleaseGroup
   */
  showSubscribe?: any;
}
