/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsSearchV2CastViewModel
 */
export interface OmbiCoreModelsSearchV2CastViewModel {
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsSearchV2CastViewModel
   */
  id?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2CastViewModel
   */
  person?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2CastViewModel
   */
  character?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2CastViewModel
   */
  image?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2CastViewModel
   */
  self?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsSearchV2CastViewModel
   */
  voice?: any;
}
