/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiSettingsSettingsModelsUpdateSettings
 */
export interface OmbiSettingsSettingsModelsUpdateSettings {
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  autoUpdateEnabled?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  username?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  password?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  processName?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  useScript?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  scriptLocation?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  windowsServiceName?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  windowsService?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  testMode?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsUpdateSettings
   */
  id?: any;
}
