/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiStoreEntitiesNotificationTemplates
 */
export interface OmbiStoreEntitiesNotificationTemplates {
  /**
   *
   * @type {OmbiHelpersNotificationType}
   * @memberof OmbiStoreEntitiesNotificationTemplates
   */
  notificationType?: any;
  /**
   *
   * @type {OmbiHelpersNotificationAgent}
   * @memberof OmbiStoreEntitiesNotificationTemplates
   */
  agent?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesNotificationTemplates
   */
  subject?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesNotificationTemplates
   */
  message?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesNotificationTemplates
   */
  enabled?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesNotificationTemplates
   */
  id?: any;
}
