/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreSettingsModelsLandingPageSettings
 */
export interface OmbiCoreSettingsModelsLandingPageSettings {
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsLandingPageSettings
   */
  enabled?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsLandingPageSettings
   */
  noticeEnabled?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreSettingsModelsLandingPageSettings
   */
  noticeText?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsLandingPageSettings
   */
  timeLimit?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiCoreSettingsModelsLandingPageSettings
   */
  startDateTime?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiCoreSettingsModelsLandingPageSettings
   */
  endDateTime?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreSettingsModelsLandingPageSettings
   */
  expired?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreSettingsModelsLandingPageSettings
   */
  id?: any;
}
