/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiStoreEntitiesRequestsMovieRequests
 */
export interface OmbiStoreEntitiesRequestsMovieRequests {
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  theMovieDbId?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  issueId?: any | null;
  /**
   *
   * @type {Array&lt;OmbiStoreEntitiesRequestsIssues&gt;}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  issues?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  subscribed?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  showSubscribe?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  rootPathOverride?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  qualityOverride?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  langCode?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  languageCode?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  requestStatus?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  imdbId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  overview?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  posterPath?: any | null;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  releaseDate?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  digitalReleaseDate?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  status?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  background?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  released?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  digitalRelease?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  title?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  approved?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  markedAsApproved?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  requestedDate?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  available?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  markedAsAvailable?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  requestedUserId?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  denied?: any | null;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  markedAsDenied?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  deniedReason?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesRequestType}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  requestType?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  requestedByAlias?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesOmbiUser}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  requestedUser?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  canApprove?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsMovieRequests
   */
  id?: any;
}
