/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiSettingsSettingsModelsCustomizationSettings
 */
export interface OmbiSettingsSettingsModelsCustomizationSettings {
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  applicationName?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  applicationUrl?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  customCss?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  enableCustomDonations?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  customDonationUrl?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  customDonationMessage?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  logo?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  recentlyAddedPage?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  useCustomPage?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  hideAvailableFromDiscover?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsCustomizationSettings
   */
  id?: any;
}
