/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiApiPlexModelsMediacontainer
 */
export interface OmbiApiPlexModelsMediacontainer {
  /**
   *
   * @type {number}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  size?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  totalSize?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  title1?: any | null;
  /**
   *
   * @type {Array&lt;OmbiApiPlexModelsDirectory&gt;}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  directory?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  art?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  librarySectionID?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  librarySectionTitle?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  librarySectionUUID?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  nocache?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  thumb?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  title2?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  viewGroup?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  viewMode?: any;
  /**
   *
   * @type {Array&lt;OmbiApiPlexModelsMetadata&gt;}
   * @memberof OmbiApiPlexModelsMediacontainer
   */
  metadata?: any | null;
}
