/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiStoreEntitiesRequestsChildRequests
 */
export interface OmbiStoreEntitiesRequestsChildRequests {
  /**
   *
   * @type {OmbiStoreEntitiesRequestsTvRequests}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  parentRequest?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  parentRequestId?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  issueId?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesRequestsSeriesType}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  seriesType?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  subscribed?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  showSubscribe?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  releaseYear?: any;
  /**
   *
   * @type {Array&lt;OmbiStoreEntitiesRequestsIssues&gt;}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  issues?: any | null;
  /**
   *
   * @type {Array&lt;OmbiStoreRepositoryRequestsSeasonRequests&gt;}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  seasonRequests?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  requestStatus?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  title?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  approved?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  markedAsApproved?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  requestedDate?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  available?: any;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  markedAsAvailable?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  requestedUserId?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  denied?: any | null;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  markedAsDenied?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  deniedReason?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesRequestType}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  requestType?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  requestedByAlias?: any | null;
  /**
   *
   * @type {OmbiStoreEntitiesOmbiUser}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  requestedUser?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  canApprove?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsChildRequests
   */
  id?: any;
}
