/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiSettingsSettingsModelsIssueSettings
 */
export interface OmbiSettingsSettingsModelsIssueSettings {
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsIssueSettings
   */
  enabled?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsIssueSettings
   */
  enableInProgress?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsIssueSettings
   */
  deleteIssues?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsIssueSettings
   */
  daysAfterResolvedToDelete?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsIssueSettings
   */
  id?: any;
}
