/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiApiRottenTomatoesModelsMovieRatings
 */
export interface OmbiApiRottenTomatoesModelsMovieRatings {
  /**
   *
   * @type {string}
   * @memberof OmbiApiRottenTomatoesModelsMovieRatings
   */
  criticsRating?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiRottenTomatoesModelsMovieRatings
   */
  criticsScore?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiRottenTomatoesModelsMovieRatings
   */
  audienceRating?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiRottenTomatoesModelsMovieRatings
   */
  audienceScore?: any;
}
