/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiModelsAboutViewModel
 */
export interface OmbiModelsAboutViewModel {
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  version?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  branch?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  frameworkDescription?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  osArchitecture?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  osDescription?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  processArchitecture?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  applicationBasePath?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  ombiDatabaseType?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  externalDatabaseType?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  settingsDatabaseType?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  ombiConnectionString?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  externalConnectionString?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  settingsConnectionString?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiModelsAboutViewModel
   */
  storagePath?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiModelsAboutViewModel
   */
  notSupported?: any;
}
