/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiApiTheMovieDbModelsCast
 */
export interface OmbiApiTheMovieDbModelsCast {
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  character?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  creditId?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  posterPath?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  id?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  video?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  voteCount?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  adult?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  backdropPath?: any | null;
  /**
   *
   * @type {Array&lt;number&gt;}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  genreIds?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  originalLanguage?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  originalTitle?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  popularity?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  title?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  voteAverage?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  overview?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiTheMovieDbModelsCast
   */
  releaseDate?: any | null;
}
