/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsUIGotifyNotificationViewModel
 */
export interface OmbiCoreModelsUIGotifyNotificationViewModel {
  /**
   *
   * @type {Array&lt;OmbiStoreEntitiesNotificationTemplates&gt;}
   * @memberof OmbiCoreModelsUIGotifyNotificationViewModel
   */
  notificationTemplates?: any | null;
  /**
   *
   * @type {boolean}
   * @memberof OmbiCoreModelsUIGotifyNotificationViewModel
   */
  enabled?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsUIGotifyNotificationViewModel
   */
  baseUrl?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsUIGotifyNotificationViewModel
   */
  applicationToken?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsUIGotifyNotificationViewModel
   */
  priority?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiCoreModelsUIGotifyNotificationViewModel
   */
  id?: any;
}
