/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiSettingsSettingsModelsNotificationsPushoverSettings
 */
export interface OmbiSettingsSettingsModelsNotificationsPushoverSettings {
  /**
   *
   * @type {boolean}
   * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
   */
  enabled?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
   */
  accessToken?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
   */
  userToken?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
   */
  priority?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
   */
  sound?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiSettingsSettingsModelsNotificationsPushoverSettings
   */
  id?: any;
}
