/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiStoreEntitiesVotes
 */
export interface OmbiStoreEntitiesVotes {
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesVotes
   */
  requestId?: any;
  /**
   *
   * @type {OmbiStoreEntitiesVoteType}
   * @memberof OmbiStoreEntitiesVotes
   */
  voteType?: any;
  /**
   *
   * @type {OmbiStoreEntitiesRequestType}
   * @memberof OmbiStoreEntitiesVotes
   */
  requestType?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesVotes
   */
  userId?: any | null;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesVotes
   */
  date?: any;
  /**
   *
   * @type {boolean}
   * @memberof OmbiStoreEntitiesVotes
   */
  deleted?: any;
  /**
   *
   * @type {OmbiStoreEntitiesOmbiUser}
   * @memberof OmbiStoreEntitiesVotes
   */
  user?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesVotes
   */
  id?: any;
}
