/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiApiJellyfinModelsPublicInfo
 */
export interface OmbiApiJellyfinModelsPublicInfo {
  /**
   *
   * @type {string}
   * @memberof OmbiApiJellyfinModelsPublicInfo
   */
  localAddress?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiJellyfinModelsPublicInfo
   */
  serverName?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiJellyfinModelsPublicInfo
   */
  version?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiJellyfinModelsPublicInfo
   */
  operatingSystem?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiApiJellyfinModelsPublicInfo
   */
  id?: any | null;
}
