/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiStoreEntitiesRequestsTvRequests
 */
export interface OmbiStoreEntitiesRequestsTvRequests {
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  tvDbId?: any;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  externalProviderId?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  imdbId?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  qualityOverride?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  rootFolder?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  languageProfile?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  overview?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  title?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  posterPath?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  background?: any | null;
  /**
   *
   * @type {Date}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  releaseDate?: any;
  /**
   *
   * @type {string}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  status?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  totalSeasons?: any;
  /**
   *
   * @type {Array&lt;OmbiStoreEntitiesRequestsChildRequests&gt;}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  childRequests?: any | null;
  /**
   *
   * @type {number}
   * @memberof OmbiStoreEntitiesRequestsTvRequests
   */
  id?: any;
}
