/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OmbiCoreModelsSearchV2MusicArtistLinks
 */
export interface OmbiCoreModelsSearchV2MusicArtistLinks {
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  image?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  imdb?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  lastFm?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  discogs?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  allMusic?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  homePage?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  youTube?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  facebook?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  twitter?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  bbcMusic?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  mySpace?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  onlineCommunity?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  spotify?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  instagram?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  vk?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  deezer?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  google?: any | null;
  /**
   *
   * @type {string}
   * @memberof OmbiCoreModelsSearchV2MusicArtistLinks
   */
  apple?: any | null;
}
