/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, RequestArgs, BaseAPI } from "../base";
import { OmbiSettingsSettingsModelsCustomPageSettings } from "../models";
/**
 * CustomPageApi - axios parameter creator
 * @export
 */
export const CustomPageApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Gets the Custom Page Settings.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1CustomPageGet: async (options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/CustomPage`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Saves the Custom Page Settings.
     * @param {OmbiSettingsSettingsModelsCustomPageSettings} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1CustomPagePost: async (
      body?: OmbiSettingsSettingsModelsCustomPageSettings,
      options: any = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/api/v1/CustomPage`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json-patch+json";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CustomPageApi - functional programming interface
 * @export
 */
export const CustomPageApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Gets the Custom Page Settings.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1CustomPageGet(
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<OmbiSettingsSettingsModelsCustomPageSettings>
    > {
      const localVarAxiosArgs = await CustomPageApiAxiosParamCreator(
        configuration
      ).apiV1CustomPageGet(options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     *
     * @summary Saves the Custom Page Settings.
     * @param {OmbiSettingsSettingsModelsCustomPageSettings} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiV1CustomPagePost(
      body?: OmbiSettingsSettingsModelsCustomPageSettings,
      options?: any
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>
    > {
      const localVarAxiosArgs = await CustomPageApiAxiosParamCreator(
        configuration
      ).apiV1CustomPagePost(body, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * CustomPageApi - factory interface
 * @export
 */
export const CustomPageApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     *
     * @summary Gets the Custom Page Settings.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1CustomPageGet(
      options?: any
    ): AxiosPromise<OmbiSettingsSettingsModelsCustomPageSettings> {
      return CustomPageApiFp(configuration)
        .apiV1CustomPageGet(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Saves the Custom Page Settings.
     * @param {OmbiSettingsSettingsModelsCustomPageSettings} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiV1CustomPagePost(
      body?: OmbiSettingsSettingsModelsCustomPageSettings,
      options?: any
    ): AxiosPromise<boolean> {
      return CustomPageApiFp(configuration)
        .apiV1CustomPagePost(body, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CustomPageApi - object-oriented interface
 * @export
 * @class CustomPageApi
 * @extends {BaseAPI}
 */
export class CustomPageApi extends BaseAPI {
  /**
   *
   * @summary Gets the Custom Page Settings.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomPageApi
   */
  public apiV1CustomPageGet(options?: any) {
    return CustomPageApiFp(this.configuration)
      .apiV1CustomPageGet(options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   *
   * @summary Saves the Custom Page Settings.
   * @param {OmbiSettingsSettingsModelsCustomPageSettings} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CustomPageApi
   */
  public apiV1CustomPagePost(
    body?: OmbiSettingsSettingsModelsCustomPageSettings,
    options?: any
  ) {
    return CustomPageApiFp(this.configuration)
      .apiV1CustomPagePost(body, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
