"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ __exportStar(require("./apis/calendar-api"), exports);
__exportStar(require("./apis/couch-potato-api"), exports);
__exportStar(require("./apis/custom-page-api"), exports);
__exportStar(require("./apis/emby-api"), exports);
__exportStar(require("./apis/hub-api"), exports);
__exportStar(require("./apis/identity-api"), exports);
__exportStar(require("./apis/images-api"), exports);
__exportStar(require("./apis/issues-api"), exports);
__exportStar(require("./apis/jellyfin-api"), exports);
__exportStar(require("./apis/job-api"), exports);
__exportStar(require("./apis/landing-page-api"), exports);
__exportStar(require("./apis/lidarr-api"), exports);
__exportStar(require("./apis/logging-api"), exports);
__exportStar(require("./apis/music-request-api"), exports);
__exportStar(require("./apis/notifications-api"), exports);
__exportStar(require("./apis/plex-api"), exports);
__exportStar(require("./apis/radarr-api"), exports);
__exportStar(require("./apis/recently-added-api"), exports);
__exportStar(require("./apis/request-api"), exports);
__exportStar(require("./apis/request-retry-api"), exports);
__exportStar(require("./apis/requests-api"), exports);
__exportStar(require("./apis/search-api"), exports);
__exportStar(require("./apis/settings-api"), exports);
__exportStar(require("./apis/sonarr-api"), exports);
__exportStar(require("./apis/stats-api"), exports);
__exportStar(require("./apis/status-api"), exports);
__exportStar(require("./apis/system-api"), exports);
__exportStar(require("./apis/tester-api"), exports);
__exportStar(require("./apis/the-movie-db-api"), exports);
__exportStar(require("./apis/token-api"), exports);
__exportStar(require("./apis/update-api"), exports);
__exportStar(require("./apis/vote-api"), exports);
//# sourceMappingURL=api.js.map