/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.7.0.17
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface EmbyScripterXPackagesPackageInfo
 */
export interface EmbyScripterXPackagesPackageInfo {
  /**
   *
   * @type {string}
   * @memberof EmbyScripterXPackagesPackageInfo
   */
  id?: any;
  /**
   *
   * @type {string}
   * @memberof EmbyScripterXPackagesPackageInfo
   */
  name?: any;
  /**
   *
   * @type {string}
   * @memberof EmbyScripterXPackagesPackageInfo
   */
  description?: any;
  /**
   *
   * @type {string}
   * @memberof EmbyScripterXPackagesPackageInfo
   */
  author?: any;
  /**
   *
   * @type {string}
   * @memberof EmbyScripterXPackagesPackageInfo
   */
  email?: any;
  /**
   *
   * @type {string}
   * @memberof EmbyScripterXPackagesPackageInfo
   */
  version?: any;
}
