/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ export * from "./apis/calendar-api";
export * from "./apis/couch-potato-api";
export * from "./apis/custom-page-api";
export * from "./apis/emby-api";
export * from "./apis/hub-api";
export * from "./apis/identity-api";
export * from "./apis/images-api";
export * from "./apis/issues-api";
export * from "./apis/jellyfin-api";
export * from "./apis/job-api";
export * from "./apis/landing-page-api";
export * from "./apis/lidarr-api";
export * from "./apis/logging-api";
export * from "./apis/music-request-api";
export * from "./apis/notifications-api";
export * from "./apis/plex-api";
export * from "./apis/radarr-api";
export * from "./apis/recently-added-api";
export * from "./apis/request-api";
export * from "./apis/request-retry-api";
export * from "./apis/requests-api";
export * from "./apis/search-api";
export * from "./apis/settings-api";
export * from "./apis/sonarr-api";
export * from "./apis/stats-api";
export * from "./apis/status-api";
export * from "./apis/system-api";
export * from "./apis/tester-api";
export * from "./apis/the-movie-db-api";
export * from "./apis/token-api";
export * from "./apis/update-api";
export * from "./apis/vote-api";
