"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenApi = exports.TokenApiFactory = exports.TokenApiFp = exports.TokenApiAxiosParamCreator = void 0;
/* tslint:disable */
/* eslint-disable */
/**
 * Ombi Api V1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
const axios_1 = require("axios");
// Some imports not used depending on template conditions
// @ts-ignore
const base_1 = require("../base");
/**
 * TokenApi - axios parameter creator
 * @export
 */
const TokenApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @param {number} pinId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenPinIdGet: async (pinId, options = {}) => {
            // verify required parameter 'pinId' is not null or undefined
            if (pinId === null || pinId === undefined) {
                throw new base_1.RequiredError("pinId", "Required parameter pinId was null or undefined when calling apiV1TokenPinIdGet.");
            }
            const localVarPath = `/api/v1/Token/{pinId}`.replace(`{${"pinId"}}`, encodeURIComponent(String(pinId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, "https://example.com");
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: "GET" }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = new URLSearchParams(query).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Returns the Token for the Ombi User if we can match the Plex user with a valid Ombi User
         * @param {OmbiModelsExternalPlexTokenAuthentication} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenPlextokenPost: async (body, options = {}) => {
            const localVarPath = `/api/v1/Token/plextoken`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, "https://example.com");
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: "POST" }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter["Content-Type"] = "application/json-patch+json";
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = new URLSearchParams(query).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            const needsSerialization = typeof body !== "string" ||
                localVarRequestOptions.headers["Content-Type"] === "application/json";
            localVarRequestOptions.data = needsSerialization
                ? JSON.stringify(body !== undefined ? body : {})
                : body || "";
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Gets the token.
         * @param {OmbiModelsUserAuthModel} [body] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenPost: async (body, options = {}) => {
            const localVarPath = `/api/v1/Token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, "https://example.com");
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: "POST" }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter["Content-Type"] = "application/json-patch+json";
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = new URLSearchParams(query).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            const needsSerialization = typeof body !== "string" ||
                localVarRequestOptions.headers["Content-Type"] === "application/json";
            localVarRequestOptions.data = needsSerialization
                ? JSON.stringify(body !== undefined ? body : {})
                : body || "";
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Refreshes the token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenRefreshPost: async (options = {}) => {
            const localVarPath = `/api/v1/Token/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, "https://example.com");
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: "POST" }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = new URLSearchParams(query).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @param {OmbiModelsUserAuthModel} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenRequirePasswordPost: async (body, options = {}) => {
            const localVarPath = `/api/v1/Token/requirePassword`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, "https://example.com");
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign(Object.assign({ method: "POST" }, baseOptions), options);
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter["Content-Type"] = "application/json-patch+json";
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = new URLSearchParams(query).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = Object.assign(Object.assign(Object.assign({}, localVarHeaderParameter), headersFromBaseOptions), options.headers);
            const needsSerialization = typeof body !== "string" ||
                localVarRequestOptions.headers["Content-Type"] === "application/json";
            localVarRequestOptions.data = needsSerialization
                ? JSON.stringify(body !== undefined ? body : {})
                : body || "";
            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    };
};
exports.TokenApiAxiosParamCreator = TokenApiAxiosParamCreator;
/**
 * TokenApi - functional programming interface
 * @export
 */
const TokenApiFp = function (configuration) {
    return {
        /**
         *
         * @param {number} pinId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TokenPinIdGet(pinId, options) {
            const localVarAxiosArgs = await (0, exports.TokenApiAxiosParamCreator)(configuration).apiV1TokenPinIdGet(pinId, options);
            return (axios = axios_1.default, basePath = base_1.BASE_PATH) => {
                const axiosRequestArgs = Object.assign(Object.assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary Returns the Token for the Ombi User if we can match the Plex user with a valid Ombi User
         * @param {OmbiModelsExternalPlexTokenAuthentication} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TokenPlextokenPost(body, options) {
            const localVarAxiosArgs = await (0, exports.TokenApiAxiosParamCreator)(configuration).apiV1TokenPlextokenPost(body, options);
            return (axios = axios_1.default, basePath = base_1.BASE_PATH) => {
                const axiosRequestArgs = Object.assign(Object.assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary Gets the token.
         * @param {OmbiModelsUserAuthModel} [body] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TokenPost(body, options) {
            const localVarAxiosArgs = await (0, exports.TokenApiAxiosParamCreator)(configuration).apiV1TokenPost(body, options);
            return (axios = axios_1.default, basePath = base_1.BASE_PATH) => {
                const axiosRequestArgs = Object.assign(Object.assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary Refreshes the token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TokenRefreshPost(options) {
            const localVarAxiosArgs = await (0, exports.TokenApiAxiosParamCreator)(configuration).apiV1TokenRefreshPost(options);
            return (axios = axios_1.default, basePath = base_1.BASE_PATH) => {
                const axiosRequestArgs = Object.assign(Object.assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @param {OmbiModelsUserAuthModel} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1TokenRequirePasswordPost(body, options) {
            const localVarAxiosArgs = await (0, exports.TokenApiAxiosParamCreator)(configuration).apiV1TokenRequirePasswordPost(body, options);
            return (axios = axios_1.default, basePath = base_1.BASE_PATH) => {
                const axiosRequestArgs = Object.assign(Object.assign({}, localVarAxiosArgs.options), { url: basePath + localVarAxiosArgs.url });
                return axios.request(axiosRequestArgs);
            };
        },
    };
};
exports.TokenApiFp = TokenApiFp;
/**
 * TokenApi - factory interface
 * @export
 */
const TokenApiFactory = function (configuration, basePath, axios) {
    return {
        /**
         *
         * @param {number} pinId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenPinIdGet(pinId, options) {
            return (0, exports.TokenApiFp)(configuration)
                .apiV1TokenPinIdGet(pinId, options)
                .then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Returns the Token for the Ombi User if we can match the Plex user with a valid Ombi User
         * @param {OmbiModelsExternalPlexTokenAuthentication} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenPlextokenPost(body, options) {
            return (0, exports.TokenApiFp)(configuration)
                .apiV1TokenPlextokenPost(body, options)
                .then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Gets the token.
         * @param {OmbiModelsUserAuthModel} [body] The model.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenPost(body, options) {
            return (0, exports.TokenApiFp)(configuration)
                .apiV1TokenPost(body, options)
                .then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Refreshes the token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenRefreshPost(options) {
            return (0, exports.TokenApiFp)(configuration)
                .apiV1TokenRefreshPost(options)
                .then((request) => request(axios, basePath));
        },
        /**
         *
         * @param {OmbiModelsUserAuthModel} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1TokenRequirePasswordPost(body, options) {
            return (0, exports.TokenApiFp)(configuration)
                .apiV1TokenRequirePasswordPost(body, options)
                .then((request) => request(axios, basePath));
        },
    };
};
exports.TokenApiFactory = TokenApiFactory;
/**
 * TokenApi - object-oriented interface
 * @export
 * @class TokenApi
 * @extends {BaseAPI}
 */
class TokenApi extends base_1.BaseAPI {
    /**
     *
     * @param {number} pinId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    apiV1TokenPinIdGet(pinId, options) {
        return (0, exports.TokenApiFp)(this.configuration)
            .apiV1TokenPinIdGet(pinId, options)
            .then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Returns the Token for the Ombi User if we can match the Plex user with a valid Ombi User
     * @param {OmbiModelsExternalPlexTokenAuthentication} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    apiV1TokenPlextokenPost(body, options) {
        return (0, exports.TokenApiFp)(this.configuration)
            .apiV1TokenPlextokenPost(body, options)
            .then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Gets the token.
     * @param {OmbiModelsUserAuthModel} [body] The model.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    apiV1TokenPost(body, options) {
        return (0, exports.TokenApiFp)(this.configuration)
            .apiV1TokenPost(body, options)
            .then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Refreshes the token.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    apiV1TokenRefreshPost(options) {
        return (0, exports.TokenApiFp)(this.configuration)
            .apiV1TokenRefreshPost(options)
            .then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @param {OmbiModelsUserAuthModel} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenApi
     */
    apiV1TokenRequirePasswordPost(body, options) {
        return (0, exports.TokenApiFp)(this.configuration)
            .apiV1TokenRequirePasswordPost(body, options)
            .then((request) => request(this.axios, this.basePath));
    }
}
exports.TokenApi = TokenApi;
//# sourceMappingURL=token-api.js.map