/* tslint:disable */
/* eslint-disable */
/**
 * Emby Server API
 * Explore the Emby Server API
 *
 * OpenAPI spec version: 4.7.0.17
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AxiosRequestConfig } from "axios";
import { UserServiceApi } from "./apis/user-service-api";
import { AuthenticationAuthenticationResult } from "./models/authentication-authentication-result";
import { lowerCaseKeys } from "../../utils";

export interface ConfigurationParameters {
  apiKey?:
    | string
    | Promise<string>
    | ((name: string) => string)
    | ((name: string) => Promise<string>);
  username?: string;
  password?: string;
  accessToken?:
    | string
    | Promise<string>
    | ((name?: string, scopes?: string[]) => string)
    | ((name?: string, scopes?: string[]) => Promise<string>);
  basePath?: string;
  baseOptions?: any;
  axiosConfig?: AxiosRequestConfig;
}

export class Configuration {
  /**
   * parameter for apiKey security
   * @param name security name
   * @memberof Configuration
   */
  apiKey?:
    | string
    | Promise<string>
    | ((name: string) => string)
    | ((name: string) => Promise<string>);
  /**
   * parameter for basic security
   *
   * @type {string}
   * @memberof Configuration
   */
  username?: string;
  /**
   * parameter for basic security
   *
   * @type {string}
   * @memberof Configuration
   */
  password?: string;
  /**
   * parameter for oauth2 security
   * @param name security name
   * @param scopes oauth2 scope
   * @memberof Configuration
   */
  accessToken?:
    | string
    | Promise<string>
    | ((name?: string, scopes?: string[]) => string)
    | ((name?: string, scopes?: string[]) => Promise<string>);
  /**
   * override base path
   *
   * @type {string}
   * @memberof Configuration
   */
  basePath?: string;
  /**
   * base options for axios calls
   *
   * @type {any}
   * @memberof Configuration
   */
  baseOptions?: any;

  axiosConfig?: AxiosRequestConfig | undefined;

  constructor(param: ConfigurationParameters = {}) {
    this.apiKey = param.apiKey;
    this.username = param.username;
    this.password = param.password;
    this.accessToken = param.accessToken;
    this.basePath = param.basePath;
    this.baseOptions = param.baseOptions;
    this.axiosConfig = param.axiosConfig;
  }

  public async init(): Promise<AuthenticationAuthenticationResult | undefined> {
    if (!this.username || !this.password) {
      throw new Error("User and Password not set");
    } else {
      const emby = new UserServiceApi(this);
      const AuthResult = await emby.postUsersAuthenticatebyname(
        {
          username: this.username,
          pw: this.password,
        },
        "",
        this.axiosConfig
      );
      const authResult: AuthenticationAuthenticationResult = lowerCaseKeys(
        AuthResult.data
      );
      this.accessToken = authResult?.accessToken;
      this.apiKey = this.accessToken;
      return authResult;
    }
  }
}
